---
name: licheervnano-host-linux-amd64-cvi-mmf-sdk-ci
on:
  workflow_dispatch:
env:
  CVI_MMF_SDK: "cvi_mmf_sdk"
jobs:
  mksys:
    strategy:
      fail-fast: false
    runs-on: ubuntu-22.04
    steps:
      - name: ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          max-size: "20G"
          create-symlink: true
          key: ${{matrix.os }}-${{ matrix.type }}
      - name: Create Timestamp
        run: |
          echo "BUILD_ID=$(date +%Y%m%d_%H%M%S)" >> "$GITHUB_ENV"
          echo "BUILD_DATE=$(date +%Y%m%d)" >> "$GITHUB_ENV"
      - name: Install Software
        run: |
          sudo apt update && \
          sudo apt install -y \
            android-libext4-utils \
            android-sdk-libsparse-utils \
            asciinema \
            autoconf \
            automake \
            autotools-dev \
            bc \
            bdebstrap \
            binutils-riscv64-unknown-elf \
            bison \
            build-essential \
            bzr \
            ca-certificates \
            ccache \
            chrpath \
            ckermit \
            cmake \
            cpio \
            cpp-riscv64-linux-gnu \
            crossbuild-essential-riscv64 \
            cscope \
            curl \
            cvs \
            debianutils \
            device-tree-compiler \
            diffstat \
            erofs-utils \
            fakechroot \
            fakeroot \
            fatcat \
            file \
            flex \
            g++-riscv64-linux-gnu \
            gawk \
            gcc-riscv64-linux-gnu \
            gcc-riscv64-unknown-elf \
            genext2fs \
            git \
            help2man \
            iputils-ping \
            jq \
            libacl1 \
            libasan8-riscv64-cross \
            libatomic1-riscv64-cross \
            libc6-dbg-riscv64-cross \
            libc6-dev-riscv64-cross \
            libconfuse-dev
            libegl1-mesa \
            liblz4-tool \
            libncurses-dev \
            libncurses5-dev \
            libsdl1.2-dev \
            libssl-dev \
            libtool-bin \
            locales \
            make \
            mercurial \
            mesa-common-dev \
            mmdebstrap \
            mtools \
            neovim \
            ninja-build \
            openssh-server \
            openssl \
            parallel \
            parted \
            picolibc-riscv64-unknown-elf \
            pkg-config \
            proot \
            python3 \
            python3-dev \
            python3-distutils \
            python3-flake8 \
            python3-git \
            python3-jinja2 \
            python3-magic \
            python3-nose2 \
            python3-pexpect \
            python3-pip \
            python3-pytest \
            python3-subunit \
            rsync \
            scons \
            shellcheck \
            slib \
            socat \
            squashfs-tools \
            ssh \
            ssh-client \
            subversion \
            tclsh \
            texinfo \
            tree \
            unzip \
            wget \
            xz-utils \
            zstd
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          path: '${{ env.CVI_MMF_SDK }}'
          ref: 'main'
          persist-credentials: false
      - name: Download Toolchain
        run: |
          export PATH="/usr/lib/ccache:/usr/local/opt/ccache/libexec:$PATH"
          pushd "${CVI_MMF_SDK}" || exit
            wget https://sophon-file.sophon.cn/sophon-prod-s3/drive/23/03/07/16/host-tools.tar.gz
            tar xf host-tools.tar.gz
          popd || exit
        env:
          CVI_MMF_SDK: ${{ env.CVI_MMF_SDK }}
      - name: Make System
        run: |
          pushd "${CVI_MMF_SDK}" || exit
            source "build/cvisetup.sh"
            defconfig sg2002_licheervnano_sd
            build_all

            # Build other variants.
            BOARD_DEFCONFIG="build/boards/sg200x/sg2002_licheervnano_sd/sg2002_licheervnano_sd_defconfig"
            cp "${BOARD_DEFCONFIG}" bak.config

            #            2.8inch,      3inch,         5inch
            for panel in "hd228001c31" "d300fpc9307a" "dxq5d0019b480854"; do
              sed -e "s/CONFIG_MIPI_PANEL_ZCT2133V1/CONFIG_MIPI_PANEL_ST7701_${panel^^}/g" "bak.config" \
                > "${BOARD_DEFCONFIG}"
              defconfig sg2002_licheervnano_sd
              clean_uboot
              clean_opensbi
              clean_fsbl
              build_fsbl
              cp -v "${CVI_MMF_SDK}/install/soc_sg2002_licheervnano_sd/fip.bin" \
                "${CVI_MMF_SDK}/install/soc_sg2002_licheervnano_sd/${panel^^}.bin"
            done

          popd || exit
        env:
          CVI_MMF_SDK: ${{ env.CVI_MMF_SDK }}
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v3
        with:
          retention-days: 30
          name: licheervnano-cvi-mmf-sdk-output-${{ env.BUILD_ID }}
          path: |
            ${{ env.CVI_MMF_SDK }}/install/soc_sg2002_licheervnano_sd/images/*
            ${{ env.CVI_MMF_SDK }}/install/soc_sg2002_licheervnano_sd/*.bin
