= Updating FFmpeg
:hide-uri-scheme:
// Enable keyboard macros
:experimental:
:toc:
:toclevels: 4
:icons: font
:note-caption: â„¹ï¸
:tip-caption: ðŸ’¡
:warning-caption: âš ï¸
:caution-caption: ðŸ”¥
:important-caption: â—

// TODO
== TODO

* Build toolchain/ask what happened to it.
* Build with https://en.wikipedia.org/wiki/Musl[musl]?
// * I have probably butchered it.

== Motivation and Observation

Version 4.4 is about 3 years old in 2024.
(https://git.ffmpeg.org/gitweb/ffmpeg.git/tags[Tags])
Will newer versions perform better?
Lets find out.

RISC-V and FFmpeg:

* https://code.videolan.org/videolan/x264/-/merge_requests/155#top -- PR open, not yet supported
* https://github.com/pion/webrtc[] -> ffmpeg
* https://github.com/pion/webrtc/tree/master/pkg/media

See the `Makefile` for implementation and building.

.Effects and Observation:
* I was not able to make out a difference, I'm still trying to evaluate the performance of the product for my usecases.
** The board has 1 CPU core and 128 MB RAM. Using it with Tailscale and H.264 1080p quickly leads to resource starvation. Tailscale is the culprit here as it wants to consume 43 MB of RAM which are practically not available.
** Monitoring? `htop`. It's preinstalled, anything more advanced is too much for this tiny board.
** Benchmarks? Real world usage.
*** I currently use it with MJPEG 720p High Quality while having `htop` open in a shell.
    Latency is acceptable, performance constant with almost no stutters or dropouts.
*** H.264 720p Low Quality is not an improvement in any way.
    Latency is higher than MJPEG, performance fluctuates with frequent stutters and occasional dropouts.
    It only gets worse on higer quality levels.

https://asciinema.org/a/6Zhv8DukEcrtfjg4wImLdTA1K[asciinema_2024-12-06_204512_nanokvm_htop.cast]

== Builds

.When I publish builds, I will publish them with tags following this schema:
* `ffmpeg-vMAJOR.MINOR.DATE-YYYYMMDD`

.Example:
* `ffmpeg-v7.1.20241206`

.Build Metrics:
* Completes in less than 5 minutes on my machine
* Dowloads less than 200 MB of data

=== RISC-V

* https://github.com/XUANTIE-RV/xuantie-gnu-toolchain/[] -> https://www.xrvm.com/
* https://forum.rvspace.org/t/ffmpeg-risc-v-port/792[] -> https://fate.ffmpeg.org/
* https://launchpad.net/ubuntu/noble/riscv64/ffmpeg

== Installation

NOTE: `nanokvm` is an alias which I configured in my `ssh_config`. You need to use whatever you have configured or the default values.

[WARNING]
====
This assumes that the library the application uses is using the `ffmpeg` command.
If it does not, then the entrie ceremony here is not effective at all.
I looked through the code, but I found no indication that the binary is called.

It may well be that the "image acquisition system" which along with the kernel has reserved memory, writes directly to the server provess in golang
====

[source,bash]
----
$ hostname
your_desktop_just_for_context

$ ssh nanokvm 
$ hostname 
kvm-xxxx

$ which ffmpeg
/usr/bin/ffmpeg

# Create a backup.
$ cp -v /usr/bin/ffmpeg /usr/bin/ffmpeg_orig
'/usr/bin/ffmpeg' -> '/usr/bin/ffmpeg_orig'

$ exit

$ hostname
your_desktop_just_for_context

# Finally install the new binary.
$ scp FFMPEG/ffmpeg-gcc-static nanokvm:/usr/bin/ffmpeg

# Reboot the server to ensure the system recognizes the new component.
$ ssh nanokvm reboot
----

== Build Configurtions

* `--enable-alsa` removed? Is is supposed to play sound?
   https://github.com/sipeed/NanoKVM/issues/100[Not yet], evetually through USB, but not through HDMI.

.Diff of `ffmpeg -buildconf` output: NanoKVM Stock vs. Custom Static Binary
[%collapsible%open]
====
[source,diff]
----
--- NanoKVM
+++ Custom
@@ -1,34 +1,33 @@
 #  ffmpeg -buildconf
-ffmpeg version 4.4.4 Copyright (c) 2000-2023 the FFmpeg developers
-  built with gcc 10.2.0 (Xuantie-900 linux-5.10.4 musl gcc Toolchain V2.6.1 B-20220906)
-  configuration: --enable-cross-compile --cross-prefix=/home/bugu/LicheeRV-Nano-Build/buildroot/output/per-package/ffmpeg/host/bin/riscv64-unknown-linux-musl- --sysroot=/home/bugu/LicheeRV-Nano-Build/buildroot/output/per-package/ffmpeg/host/riscv64-buildroot-linux-musl/sysroot --host-cc='/home/bugu/LicheeRV-Nano-Build/buildroot/output/per-package/ffmpeg/host/bin/ccache /usr/bin/gcc' --arch=riscv64 --target-os=linux --disable-stripping --pkg-config=/home/bugu/LicheeRV-Nano-Build/buildroot/output/per-package/ffmpeg/host/bin/pkg-config --disable-static --enable-shared --prefix=/usr --enable-avfilter --disable-version3 --enable-logging --enable-optimizations --disable-extra-warnings --enable-avdevice --enable-avcodec --enable-avformat --enable-network --disable-gray --enable-swscale-alpha --disable-small --enable-dct --enable-fft --enable-mdct --enable-rdft --disable-crystalhd --disable-dxva2 --enable-runtime-cpudetect --disable-hardcoded-tables --disable-mipsdsp --disable-mipsdspr2 --disable-msa --enable-hwaccels --disable-cuda --disable-cuvid --disable-nvenc --disable-avisynth --disable-frei0r --disable-libopencore-amrnb --disable-libopencore-amrwb --disable-libdc1394 --disable-libgsm --disable-libilbc --disable-libvo-amrwbenc --disable-symver --disable-doc --enable-gpl --enable-nonfree --enable-ffmpeg --disable-ffplay --disable-libv4l2 --enable-avresample --enable-ffprobe --disable-libxcb --enable-postproc --enable-swscale --enable-indevs --enable-alsa --enable-outdevs --enable-pthreads --enable-zlib --enable-bzlib --disable-libfdk-aac --disable-libcdio --disable-gnutls --enable-openssl --disable-libdrm --disable-libopenh264 --disable-vaapi --disable-vdpau --disable-mmal --disable-omx --disable-omx-rpi --disable-libopencv --disable-libopus --disable-libvpx --disable-libass --disable-libbluray --disable-libmfx --disable-librtmp --disable-libmp3lame --disable-libmodplug --disable-libspeex --disable-libtheora --disable-iconv --disable-libfreetype --disable-fontconfig --disable-libopenjpeg --disable-libx264 --disable-libx265 --disable-libdav1d --disable-x86asm --disable-mmx --disable-sse --disable-sse2 --disable-sse3 --disable-ssse3 --disable-sse4 --disable-sse42 --disable-avx --disable-avx2 --disable-armv6 --disable-armv6t2 --disable-vfp --disable-neon --disable-altivec --extra-libs=-latomic --enable-pic --cpu=rv64imafdc
-  libavutil      56. 70.100 / 56. 70.100
-  libavcodec     58.134.100 / 58.134.100
-  libavformat    58. 76.100 / 58. 76.100
-  libavdevice    58. 13.100 / 58. 13.100
-  libavfilter     7.110.100 /  7.110.100
-  libavresample   4.  0.  0 /  4.  0.  0
-  libswscale      5.  9.100 /  5.  9.100
-  libswresample   3.  9.100 /  3.  9.100
-  libpostproc    55.  9.100 / 55.  9.100
+ffmpeg version 364f6a5 Copyright (c) 2000-2024 the FFmpeg developers
+  built with gcc 13 (Ubuntu 13.2.0-23ubuntu4)
+  configuration: --arch=riscv64 --cpu=rv64imafdc --cross-prefix=riscv64-linux-gnu- --disable-altivec --disable-armv6 --disable-armv6t2 --disable-avisynth --disable-avx --disable-avx2 --disable-cuda --disable-cuvid --disable-doc --disable-dxva2 --disable-extra-warnings --disable-ffplay --disable-ffprobe --disable-fontconfig --disable-frei0r --disable-gnutls --disable-gray --disable-hardcoded-tables --disable-iconv --disable-libass --disable-libbluray --disable-libcdio --disable-libdav1d --disable-libdc1394 --disable-libdrm --disable-libfdk-aac --disable-libfreetype --disable-libgsm --disable-libilbc --disable-libmfx --disable-libmodplug --disable-libmp3lame --disable-libopencore-amrnb --disable-libopencore-amrwb --disable-libopencv --disable-libopenh264 --disable-libopenjpeg --disable-libopus --disable-librtmp --disable-libspeex --disable-libtheora --disable-libv4l2 --disable-libvo-amrwbenc --disable-libvpx --disable-libx264 --disable-libx265 --disable-libxcb --disable-mipsdsp --disable-mipsdspr2 --disable-mmal --disable-mmx --disable-msa --disable-manpages --disable-neon --disable-nvenc --disable-omx --disable-omx-rpi --disable-shared --disable-small --disable-sse --disable-sse2 --disable-sse3 --disable-sse4 --disable-sse42 --disable-ssse3 --disable-symver --disable-vaapi --disable-vdpau --disable-version3 --disable-vfp --disable-x86asm --enable-avcodec --enable-avdevice --enable-avfilter --enable-avformat --enable-cross-compile --enable-ffmpeg --enable-gpl --enable-hwaccels --enable-indevs --enable-logging --enable-network --enable-nonfree --enable-optimizations --enable-outdevs --enable-pic --enable-postproc --enable-pthreads --enable-runtime-cpudetect --enable-static --enable-swscale --enable-swscale-alpha --enable-zlib --extra-libs=-latomic --pkg-config-flags=--static --extra-cflags='-static -O3 -fPIC -I/home/bt/PROJECTS/ffmpeg_riscv64/build/sysroot/include' --extra-ldflags='-static -L/home/bt/PROJECTS/ffmpeg_riscv64/build/sysroot/lib' --pkg-config-flags=--static --prefix=/usr --sysroot=/home/bt/PROJECTS/ffmpeg_riscv64/build/sysroot --target-os=linux
+  libavutil      59. 39.100 / 59. 39.100
+  libavcodec     61. 19.101 / 61. 19.101
+  libavformat    61.  7.100 / 61.  7.100
+  libavdevice    61.  3.100 / 61.  3.100
+  libavfilter    10.  4.100 / 10.  4.100
+  libswscale      8.  3.100 /  8.  3.100
+  libswresample   5.  3.100 /  5.  3.100
+  libpostproc    58.  3.100 / 58.  3.100
 
   configuration:
     --arch=riscv64
     --cpu=rv64imafdc
-    --cross-prefix=/home/bugu/LicheeRV-Nano-Build/buildroot/output/per-package/ffmpeg/host/bin/riscv64-unknown-linux-musl-
+    --cross-prefix=riscv64-linux-gnu-
     --disable-altivec
     --disable-armv6
     --disable-armv6t2
     --disable-avisynth
     --disable-avx
     --disable-avx2
-    --disable-crystalhd
     --disable-cuda
     --disable-cuvid
     --disable-doc
     --disable-dxva2
     --disable-extra-warnings
     --disable-ffplay
+    --disable-ffprobe
     --disable-fontconfig
     --disable-frei0r
     --disable-gnutls
@@ -63,6 +62,7 @@
     --disable-libx264
     --disable-libx265
     --disable-libxcb
+    --disable-manpages
     --disable-mipsdsp
     --disable-mipsdspr2
     --disable-mmal
@@ -72,6 +72,7 @@
     --disable-nvenc
     --disable-omx
     --disable-omx-rpi
+    --disable-shared
     --disable-small
     --disable-sse
     --disable-sse2
@@ -79,47 +80,38 @@
     --disable-sse4
     --disable-sse42
     --disable-ssse3
-    --disable-stripping
     --disable-symver
     --disable-vaapi
     --disable-vdpau
     --disable-version3
     --disable-vfp
     --disable-x86asm
-    --enable-alsa
     --enable-avcodec
     --enable-avdevice
     --enable-avfilter
     --enable-avformat
-    --enable-avresample
-    --enable-bzlib
     --enable-cross-compile
-    --enable-dct
     --enable-ffmpeg
-    --enable-ffprobe
-    --enable-fft
     --enable-gpl
     --enable-hwaccels
     --enable-indevs
     --enable-logging
-    --enable-mdct
     --enable-network
     --enable-nonfree
-    --enable-openssl
     --enable-optimizations
     --enable-outdevs
     --enable-pic
     --enable-postproc
     --enable-pthreads
-    --enable-rdft
     --enable-runtime-cpudetect
-    --enable-shared
+    --enable-static
     --enable-swscale
     --enable-swscale-alpha
     --enable-zlib
+    --extra-cflags='-static -O3 -fPIC -I/home/bt/PROJECTS/ffmpeg_riscv64/build/sysroot/include'
+    --extra-ldflags='-static -L/home/bt/PROJECTS/ffmpeg_riscv64/build/sysroot/lib'
     --extra-libs=-latomic
-    --host-cc='/home/bugu/LicheeRV-Nano-Build/buildroot/output/per-package/ffmpeg/host/bin/ccache /usr/bin/gcc'
-    --pkg-config=/home/bugu/LicheeRV-Nano-Build/buildroot/output/per-package/ffmpeg/host/bin/pkg-config --disable-static
+    --pkg-config-flags=--static
     --prefix=/usr
-    --sysroot=/home/bugu/LicheeRV-Nano-Build/buildroot/output/per-package/ffmpeg/host/riscv64-buildroot-linux-musl/sysroot
+    --sysroot=/home/bt/PROJECTS/ffmpeg_riscv64/build/sysroot
     --target-os=linux
----
====

.Complete original `ffmpeg -buildconf` output for future reference
[%collapsible]
====
----
#  ffmpeg -buildconf
ffmpeg version 4.4.4 Copyright (c) 2000-2023 the FFmpeg developers
  built with gcc 10.2.0 (Xuantie-900 linux-5.10.4 musl gcc Toolchain V2.6.1 B-20220906)
  configuration: --enable-cross-compile --cross-prefix=/home/bugu/LicheeRV-Nano-Build/buildroot/output/per-package/ffmpeg/host/bin/riscv64-unknown-linux-musl- --sysroot=/home/bugu/LicheeRV-Nano-Build/buildroot/output/per-package/ffmpeg/host/riscv64-buildroot-linux-musl/sysroot --host-cc='/home/bugu/LicheeRV-Nano-Build/buildroot/output/per-package/ffmpeg/host/bin/ccache /usr/bin/gcc' --arch=riscv64 --target-os=linux --disable-stripping --pkg-config=/home/bugu/LicheeRV-Nano-Build/buildroot/output/per-package/ffmpeg/host/bin/pkg-config --disable-static --enable-shared --prefix=/usr --enable-avfilter --disable-version3 --enable-logging --enable-optimizations --disable-extra-warnings --enable-avdevice --enable-avcodec --enable-avformat --enable-network --disable-gray --enable-swscale-alpha --disable-small --enable-dct --enable-fft --enable-mdct --enable-rdft --disable-crystalhd --disable-dxva2 --enable-runtime-cpudetect --disable-hardcoded-tables --disable-mipsdsp --disable-mipsdspr2 --disable-msa --enable-hwaccels --disable-cuda --disable-cuvid --disable-nvenc --disable-avisynth --disable-frei0r --disable-libopencore-amrnb --disable-libopencore-amrwb --disable-libdc1394 --disable-libgsm --disable-libilbc --disable-libvo-amrwbenc --disable-symver --disable-doc --enable-gpl --enable-nonfree --enable-ffmpeg --disable-ffplay --disable-libv4l2 --enable-avresample --enable-ffprobe --disable-libxcb --enable-postproc --enable-swscale --enable-indevs --enable-alsa --enable-outdevs --enable-pthreads --enable-zlib --enable-bzlib --disable-libfdk-aac --disable-libcdio --disable-gnutls --enable-openssl --disable-libdrm --disable-libopenh264 --disable-vaapi --disable-vdpau --disable-mmal --disable-omx --disable-omx-rpi --disable-libopencv --disable-libopus --disable-libvpx --disable-libass --disable-libbluray --disable-libmfx --disable-librtmp --disable-libmp3lame --disable-libmodplug --disable-libspeex --disable-libtheora --disable-iconv --disable-libfreetype --disable-fontconfig --disable-libopenjpeg --disable-libx264 --disable-libx265 --disable-libdav1d --disable-x86asm --disable-mmx --disable-sse --disable-sse2 --disable-sse3 --disable-ssse3 --disable-sse4 --disable-sse42 --disable-avx --disable-avx2 --disable-armv6 --disable-armv6t2 --disable-vfp --disable-neon --disable-altivec --extra-libs=-latomic --enable-pic --cpu=rv64imafdc
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100

  configuration:
    --arch=riscv64
    --cpu=rv64imafdc
    --cross-prefix=/home/bugu/LicheeRV-Nano-Build/buildroot/output/per-package/ffmpeg/host/bin/riscv64-unknown-linux-musl-
    --disable-altivec
    --disable-armv6
    --disable-armv6t2
    --disable-avisynth
    --disable-avx
    --disable-avx2
    --disable-crystalhd
    --disable-cuda
    --disable-cuvid
    --disable-doc
    --disable-dxva2
    --disable-extra-warnings
    --disable-ffplay
    --disable-fontconfig
    --disable-frei0r
    --disable-gnutls
    --disable-gray
    --disable-hardcoded-tables
    --disable-iconv
    --disable-libass
    --disable-libbluray
    --disable-libcdio
    --disable-libdav1d
    --disable-libdc1394
    --disable-libdrm
    --disable-libfdk-aac
    --disable-libfreetype
    --disable-libgsm
    --disable-libilbc
    --disable-libmfx
    --disable-libmodplug
    --disable-libmp3lame
    --disable-libopencore-amrnb
    --disable-libopencore-amrwb
    --disable-libopencv
    --disable-libopenh264
    --disable-libopenjpeg
    --disable-libopus
    --disable-librtmp
    --disable-libspeex
    --disable-libtheora
    --disable-libv4l2
    --disable-libvo-amrwbenc
    --disable-libvpx
    --disable-libx264
    --disable-libx265
    --disable-libxcb
    --disable-mipsdsp
    --disable-mipsdspr2
    --disable-mmal
    --disable-mmx
    --disable-msa
    --disable-neon
    --disable-nvenc
    --disable-omx
    --disable-omx-rpi
    --disable-small
    --disable-sse
    --disable-sse2
    --disable-sse3
    --disable-sse4
    --disable-sse42
    --disable-ssse3
    --disable-stripping
    --disable-symver
    --disable-vaapi
    --disable-vdpau
    --disable-version3
    --disable-vfp
    --disable-x86asm
    --enable-alsa
    --enable-avcodec
    --enable-avdevice
    --enable-avfilter
    --enable-avformat
    --enable-avresample
    --enable-bzlib
    --enable-cross-compile
    --enable-dct
    --enable-ffmpeg
    --enable-ffprobe
    --enable-fft
    --enable-gpl
    --enable-hwaccels
    --enable-indevs
    --enable-logging
    --enable-mdct
    --enable-network
    --enable-nonfree
    --enable-openssl
    --enable-optimizations
    --enable-outdevs
    --enable-pic
    --enable-postproc
    --enable-pthreads
    --enable-rdft
    --enable-runtime-cpudetect
    --enable-shared
    --enable-swscale
    --enable-swscale-alpha
    --enable-zlib
    --extra-libs=-latomic
    --host-cc='/home/bugu/LicheeRV-Nano-Build/buildroot/output/per-package/ffmpeg/host/bin/ccache /usr/bin/gcc'
    --pkg-config=/home/bugu/LicheeRV-Nano-Build/buildroot/output/per-package/ffmpeg/host/bin/pkg-config --disable-static
    --prefix=/usr
    --sysroot=/home/bugu/LicheeRV-Nano-Build/buildroot/output/per-package/ffmpeg/host/riscv64-buildroot-linux-musl/sysroot
    --target-os=linux
----
====
