= Building entire firmware images
:hide-uri-scheme:
// Enable keyboard macros
:experimental:
:toc:
:toclevels: 4
:icons: font
:note-caption: â„¹ï¸
:tip-caption: ðŸ’¡
:warning-caption: âš ï¸
:caution-caption: ðŸ”¥
:important-caption: â—

== Info

Since I wasn't sure if FFmpeg is used at all I wanted to create an entire new image and see how it performs.
It tunred out that the official image in version 1.3 had been released 2 weeks ago, which increased the amount of available RAm, but it was not recgnized by the updater.
On the ohter hand I realized I could make the scripts build FFmpeg version 5 instead of 4, but the resulting image would still have version 4.
So we are at a wild mix of different things.
The official image has the latest app and fixes.
The updated image has most security patches.
FFmpeg can be built in version 7 as a static binary with GCC.

TODO: Try to build FFmpeg with musl.

* https://stackoverflow.com/questions/74424444/how-to-build-a-rust-program-for-riscv64gc-unknown-linux-musl#74450463
** https://github.com/riscv-collab/riscv-gnu-toolchain
** Or: https://musl.cc/[] -> https://musl.cc/riscv64-linux-musl-cross.tgz
* https://github.com/scpcom/LicheeSG-Nano-Build/tree/develop

== Building the image

* Compiling the toolchain takes about 2 hours and is not worth it when it can be fetched and unpacked inh less the n1 minute.
* Image can be compled on my workstation in less than 30 minutes.
* As mentioned above, the extra effort to compile a newer version of FFmpeg is not worth it, since it gets replaced by some yet unkown mechanism.

----
# Start off the build process:
make

# The process will run into an error which I don't know how to fix yet.
# Paste the commands below to continue.
export PATH=${PWD}/riscv64-linux-musl-cross/bin:$PATH
cd LicheeSG-Nano-Build && time ./build-nanokvm.sh
----
